kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: loki-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  replicaAutoBalance: "least-effort"
  fsType: "ext4"