---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 5.8.9
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    #https://grafana.com/docs/loki/latest/installation/helm/reference/
    backend:
      image:
        tag: latest
      persistence:
        storageClass: loki-storage-class
      replicas: 2
    read:
      image:
        tag: latest
      persistence:
        storageClass: loki-storage-class
    singleBinary:
      image:
        tag: latest
      persistence:
        storageClass: loki-storage-class
    test:
      image:
        tag: latest
    write:
      image:
        tag: latest
      persistence:
        storageClass: loki-storage-class
    gateway:
      image:
        tag: latest
      # Gateway ingress configuration
      ingress:
        # -- Specifies whether an ingress for the gateway should be created
        enabled: true
        # -- Ingress Class Name. MAY be required for Kubernetes versions >= 1.18
        ingressClassName: ""
        # -- Annotations for the gateway ingress
        annotations: 
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          field.cattle.io/publicEndpoints: '[{"addresses":["${METALLB_TRAEFIK_ADDR}"],"port":443,"protocol":"HTTPS","serviceName":"observability:loki","ingressName":"observability:loki","hostname":"gateway-loki.${CLUSTER_DOMAIN}","allNodes":false}]'
          meta.helm.sh/release-name: grafana
          meta.helm.sh/release-namespace: observability
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        # -- Hosts configuration for the gateway ingress
        hosts:
          - host: gateway-loki.${CLUSTER_DOMAIN}
            paths:
              - path: /
                # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.) might also be required by some Ingress Controllers
                # pathType: Prefix
        # -- TLS configuration for the gateway ingress
        tls:
          - secretName: loki-gateway-tls
            hosts:
              - gateway-loki.${CLUSTER_DOMAIN}
    kubectlImage: 
      tag: latest
    loki:
      image:
        tag: main
    monitoring:
      lokiCanary:
        enabled: false
      selfMonitoring:
        enabled: false
