---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cert-manager
spec: 
  interval: 1h
  dependsOn:
    - name: rancher
      namespace: core
  chart:
    spec:
      # renovate: registryUrl=https://cloudflare.github.io/origin-ca-issuer/charts
      chart: cloudflared
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: franaraujo77-charts
        namespace: flux-system
  values:
    replicaCount: 2
    args:
      tokenSecret: service-key
      tokenKey: ZEROTRUST_KEY
