apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #renovate: registryUrl=https://cloudflare.github.io/origin-ca-issuer/charts
  - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/v0.6.1/deploy/crds/cert-manager.k8s.cloudflare.com_originissuers.yaml
