apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - rancher.yaml
  - cloudflare-originca-sops.env
  - rancher-bootstrap-sops.env
secretGenerator:
- name: service-key
  namespace: cattle-system
  options:
    disableNameSuffixHash: true
  envs:
  - cloudflare-originca-sops.env
- name: bootstrap-secret
  namespace: cattle-system
  options:
    disableNameSuffixHash: true
  envs:
  - rancher-bootstrap-sops.env