apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - rancher.yaml
secretGenerator:
- name: service-key
  namespace: cattle-system
  literals:
  - key=${SECRET_CLOUDFLARE_ORIGINCA_APIKEY}