kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vscode-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: openebs-jiva-csi-default
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  replicaAutoBalance: "least-effort"
  fsType: "ext4"
  nodeSelector: "!node-role.kubernetes.io/master"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vscode-storage-class
  resources:
    requests:
      storage: 5Gi