---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: apps
spec:
  interval: 5m
  dependsOn:
    - name: home-assistant
      namespace: apps
  chart:
    spec:
      # renovate: registryUrl=https://nicholaswilde.github.io/helm-charts/
      chart: code-server
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: code-server-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    extraArgs:
      - --user-data-dir
      - /data/config/.vscode
    image:
      repository: ghcr.io/linuxserver/code-server
      tag: "version-v3.11.1"
    service:
      enabled: true
      type: ClusterIP
      port:
        port: 8443
    env:
      PUID: "1000"
      PGID: "1000"
      #PROXY_DOMAIN: ${SECRET_DOMAIN}
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: prod-issuer
        cert-manager.io/issuer-kind: OriginIssuer
        cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
        field.cattle.io/publicEndpoints: '[{"addresses":["${METALLB_TRAEFIK_ADDR}"],"port":443,"protocol":"HTTPS","serviceName":"apps:code-server","ingressName":"apps:code-server","hostname":"vscode.${CLUSTER_DOMAIN}","allNodes":false}]'
        meta.helm.sh/release-name: code-server
        meta.helm.sh/release-namespace: apps
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - host: vscode.${CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - vscode.${CLUSTER_DOMAIN}
          secretName: "code-server-tls"
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-data
        mountPath: /data/config
