---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx
  namespace: apps
spec:
  interval: 10m
  dependsOn:
    - name: home-assistant
      namespace: apps
  chart:
    spec:
      # renovate: registryUrl=https://repos.emqx.io/charts
      chart: emqx
      version: 5.3.1
      sourceRef:
        kind: HelmRepository
        name: emqx-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      tag: "latest"
    ingress:
      dashboard:
        enabled: true
        class: traefik
        annotations:
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          field.cattle.io/publicEndpoints: '[{"addresses":["${METALLB_TRAEFIK_ADDR}"],"port":443,"protocol":"HTTPS","serviceName":"apps:emqx","ingressName":"apps:emqx","hostname":"emqx.${CLUSTER_DOMAIN}","allNodes":false}]'
          meta.helm.sh/release-name: emqx
          meta.helm.sh/release-namespace: apps
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts: 
          - emqx.${CLUSTER_DOMAIN}
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - emqx.${CLUSTER_DOMAIN}
            secretName: "emqx-tls"
      mqtt:
        enabled: true
        class: traefik
        annotations:
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          field.cattle.io/publicEndpoints: '[{"addresses":["${METALLB_TRAEFIK_ADDR}"],"port":443,"protocol":"HTTPS","serviceName":"apps:emqx","ingressName":"apps:emqx","hostname":"mqttemqx.${CLUSTER_DOMAIN}","allNodes":false}]'
          meta.helm.sh/release-name: emqx
          meta.helm.sh/release-namespace: apps
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts: 
          - mqttemqx.${CLUSTER_DOMAIN}
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - mqttemqx.${CLUSTER_DOMAIN}
            secretName: "mqtt-emqx-tls"
