---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.57.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: grafana/grafana
      # Overrides the Grafana image tag whose default is the chart appVersion
      tag: ""
      pullPolicy: IfNotPresent
    replicas: 1
    env:
      GF_EXPLORE_ENABLED: true
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_LOG_FILTERS: rendering:debug
      GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
      GF_DATE_FORMATS_FULL_DATE: "MMM Do, YYYY hh:mm:ss a"
      GF_DATE_FORMATS_INTERVAL_SECOND: "hh:mm:ss a"
      GF_DATE_FORMATS_INTERVAL_MINUTE: "hh:mm a"
      GF_DATE_FORMATS_INTERVAL_HOUR: "DD/MM hh:mm a"
      GF_DATE_FORMATS_INTERVAL_DAY: "DD/MM"
      GF_DATE_FORMATS_INTERVAL_MONTH: "MM-YYYY"
      GF_DATE_FORMATS_INTERVAL_YEAR: "YYYY"
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    grafana.ini:
      server:
        root_url: "https://grafana.${CLUSTER_DOMAIN}"
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      #auth.basic:
        #disable_login_form: false
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus-prometheus.observability:9090
            isDefault: true
            editable: true
          - name: Loki
            type: loki
            uid: loki
            access: proxy
            url: http://loki.observability:3100
            editable: true
          - name: Jaeger
            type: jaeger
            access: proxy
            url: http://jaeger-query.observability:16686
            editable: true
            jsonData:
              tracesToLogs:
                datasourceUid: loki
                tags:
                  - cluster
                  - hostname
                  - namespace
                  - pod
          - name: InfluxDB
            type: influxdb
            access: proxy
            url: http://influxdb-influxdb2.database:80
            secureJsonData:
              token: wgXSklpkhpbZXGEZvojQhwPH-l_bc1dipFksMbvVoePLzdZlKCZoMSgUwVV2UFACaQa0egMiGVwX58S2vcBm1A==
            jsonData:
              version: Flux
              organization: influxdata
              defaultBucket: home-assistant
            editable: true
            basicAuth: false
    dashboards:
      default:
        # Ref: https://grafana.com/grafana/dashboards/11315
        #unifi-client-insights:
          #gnetId: 11315
          #revision: 8
          #datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11311
        #unifi-network-sites:
          #gnetId: 11311
          #revision: 4
          #datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11314
        #unifi-uap-insights:
          #gnetId: 11314
          #revision: 9
          #datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11312
        #unifi-usw-insights:
          #gnetId: 11312
          #revision: 8
          #datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/13665
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
          datasource: Prometheus
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/14900
        traefik:
          gnetId: 14900
          revision: 3
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/10001
        jaeger:
          gnetId: 10001
          revision: 2
          datasource: Prometheus
        #apc-smart-ups-1500:
          #url: https://raw.githubusercontent.com/k8s-at-home/grafana-dashboards/main/apc-smart-ups-1500-snmp.json
          #datasource: Prometheus
        #cyberpower-pdu41001:
          #url: https://raw.githubusercontent.com/k8s-at-home/grafana-dashboards/main/cyberpower-pdu41001-snmp.json
          #datasource: Prometheus
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - grafana-worldmap-panel
      - grafana-clock-panel
      - grafana-googlesheets-datasource
    #serviceMonitor:
      #enabled: true
    ingress:
      enabled: true
      annotations:
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          field.cattle.io/publicEndpoints: '[{"addresses":["${METALLB_TRAEFIK_ADDR}"],"port":443,"protocol":"HTTPS","serviceName":"observability:grafana","ingressName":"observability:grafana","hostname":"grafana.${CLUSTER_DOMAIN}","allNodes":false}]'
          meta.helm.sh/release-name: grafana
          meta.helm.sh/release-namespace: observability
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - "grafana.${CLUSTER_DOMAIN}"
      tls:
        - hosts:
            - "grafana.${CLUSTER_DOMAIN}"
          secretName: "grafana-tls"
    #serviceAccount:
      #create: true
      #autoMount: true
    persistence:
      enabled: false
