---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.15.100-192.168.15.247
  METALLB_TRAEFIK_ADDR: 192.168.15.249
  CLUSTER_DOMAIN: karva.work
