apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-elastic
  namespace: observability
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
volumeBindingMode: WaitForFirstConsumer
parameters:
  pathPattern: "apps/nfs-client-elastic"
  onDelete: retain
  accessModes: ReadWriteMany