---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://helm.elastic.co
      chart: eck-operator
      version: 2.8.0
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
      interval: 5m
  values:
    # https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-install-helm.html
    installCRDs: false
    webhook:
      certManagerCert: elastic-karva
    podMonitor:
      enabled: true
      namespace: observability