---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: core
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    # Declare values passed into templates.
    longhornManager:
      priorityClass: ~
      nodeSelector: 
      - node-role.kubernetes.io/master: "false"

    longhornDriver:
      priorityClass: ~
      nodeSelector: 
      - node-role.kubernetes.io/master: "false"

    longhornUI:
      priorityClass: ~
      nodeSelector: 
      - node-role.kubernetes.io/master: "false"