---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: core
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    # Declare values passed into templates.
    longhornManager:
      priorityClass: ~
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: true
        effect: NoSchedule

    longhornDriver:
      priorityClass: ~
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: true
        effect: NoSchedule

    longhornUI:
      priorityClass: ~
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: true
        effect: NoSchedule 