---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chronograf
  namespace: database
spec:
  interval: 10m
  releaseName: chronograf
  dependsOn:
    - name: influxdb
      namespace: database
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: chronograf
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    service:
      type: ClusterIP
      port: 80
      targetPort: 8086
      portName: http
    ingress:
      enabled: true
      annotations:
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          field.cattle.io/publicEndpoints: '[{"addresses":["${METALLB_TRAEFIK_ADDR}"],"port":443,"protocol":"HTTPS","serviceName":"database:chronograf","ingressName":"database:chronograf","hostname":"chronograf.${CLUSTER_DOMAIN}","allNodes":false}]'
          meta.helm.sh/release-name: chronograf
          meta.helm.sh/release-namespace: database
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hostname: chronograf.${CLUSTER_DOMAIN}
      path: /
      tls: true
      secretName: chronograf-tls
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
    persistence:
      enabled: true
      storageClass: nfs-client-chronograf
      size: 10Gi
    influxdb:
      existingSecret: influxdb-influxdb2-auth