---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: core
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-charts
        namespace: flux-system
  values:
    nfs:
      server: ${NFS_SERVER_ADDRESS}
      path: ${NFS_SHARE_FOLDER}
    storageClass:
      provisionerName: k8s-sigs.io/nfs-subdir-external-provisioner
      onDelete: retain
      accessModes: ReadWriteMany
      volumeBindingMode: WaitForFirstConsumer
      