---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: ${METALLB_LB_RANGE}
  METALLB_TRAEFIK_ADDR: ${METALLB_TRAEFIK_ADDR}
  CLUSTER_DOMAIN: ${CLOUDFLARE_DOMAIN}
  NFS_SERVER_ADDRESS: ${NFS_SERVER_ADDRESS}
  NFS_SHARE_FOLDER: ${NFS_SHARE_FOLDER}
