---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kapacitor
  namespace: database
spec:
  releaseName: kapacitor
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: kapacitor
      version: 1.6.4
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    service:
      type: ClusterIP
      port: 80
      targetPort: 8086
      portName: http
    ingress:
      enabled: true
      annotations:
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          field.cattle.io/publicEndpoints: '[{"addresses":["${METALLB_TRAEFIK_ADDR}"],"port":443,"protocol":"HTTPS","serviceName":"database:kapacitor","ingressName":"database:kapacitor","hostname":"kapacitor.${CLUSTER_DOMAIN}","allNodes":false}]'
          meta.helm.sh/release-name: kapacitor
          meta.helm.sh/release-namespace: database
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hostname: kapacitor.${CLUSTER_DOMAIN}
      path: /
      tls: true
      secretName: kapacitor-tls
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
    persistence:
      enabled: true
      existingClaim: kapacitor-data
    influxURL: http://influxdb-influxdb2-0
    existingSecret: influxdb-influxdb2-auth
    sidecar:
      skipTlsVerify: true
      sideload:
        enabled: true