apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: prod-issuer
  namespace: apps
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: service-key
      key: key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hass-karva
  namespace: apps
spec:
  # The secret name where cert-manager should store the signed certificate
  secretName: hass-karva-tls
  dnsNames:
    - hass.${CLUSTER_DOMAIN}
  # Duration of the certificate
  duration: 1680h
  # Renew a day before the certificate expiration
  renewBefore: 24h
  # Reference the Origin CA Issuer you created above, which must be in the same namespace.
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: prod-issuer