
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  server_host: 0.0.0.0
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
  # Pod CIDR
  - 10.0.0.0/8
  # Node CIDR
  - 192.168.0.0/16

influxdb:
  api_version: 2
  ssl: false
  host: influxdb.database
  #host: influxdb.apps
  port: 8086
  token: wgXSklpkhpbZXGEZvojQhwPH-l_bc1dipFksMbvVoePLzdZlKCZoMSgUwVV2UFACaQa0egMiGVwX58S2vcBm1A==
  organization: 8f380de9376985bb
  bucket: home-assistant
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
  exclude:
    entities:
      - zone.home
    domains:
      - persistent_notification
      - person
  include:
    domains:
      - sensor
      - binary_sensor
    entities:
      - weather.home

# Example tplink-kasa entry with manually specified addresses(or hostnames)
tplink:
  discovery: false
  switch:
    - host: 192.168.1.197
  strip:
    - host: 192.168.1.166
    - host: 192.168.1.141