apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: influxdb-karva
  namespace: database
spec:
  # The secret name where cert-manager should store the signed certificate
  secretName: influxdb-karva-tls
  dnsNames:
    - influxdb.${CLUSTER_DOMAIN}
  # Duration of the certificate
  duration: 1680h
  # Renew a day before the certificate expiration
  renewBefore: 24h
  # Reference the Origin CA Issuer you created above, which must be in the same namespace.
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: prod-issuer