name: Broken Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Run lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: . --exclude-all-private --exclude .png --max-concurrency=24 --no-progress --verbose
          # Fail action on broken links
          fail: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create GitHub Issue From lychee output file
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
