name: Schedule - Renovate Helm Releases

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "false"
        required: false
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json5"
      - ".github/renovate/**.json"

env:
  LOG_LEVEL: debug
  DRY_RUN: false

jobs:
  renovate-helm-releases:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      #- name: Verify Renovate Configuration
        #uses: tj-actions/renovate-config-validator@v1.3
      #- name: Validate
        #uses: rinchsan/renovate-config-validator@v0.0.12
        #with:
          #config-file: .github/renovate.json5
      - name: Self-hosted Renovate for Helm Release Updates
        uses: renovatebot/github-action@v39.1.3
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}